services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: jobboard_user
      POSTGRES_PASSWORD: jobboard_password
      POSTGRES_DB: jobboard_local
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
